DOMAIN = "kobold_vr7"
CONF_EMAIL = "email"
CONF_OTP = "otp"
CONF_ID_TOKEN = "id_token"
ORBITAL_HOST = "https://orbital.ksecosys.com"
AUTH_HOST = "https://mykobold.eu.auth0.com"
SIGNAL_ROBOT_BATTERY = "kobold_vr7_battery"
