# Servicio para limpiar una zona específica
clean_zone:
  name: Clean zones
  description: Start cleaning one or multiple specific zones (from the same map).
  target:
    entity:
      domain: vacuum
      integration: kobold_vr7
  fields:
    zones_uuid:
      name: Zones UUID
      description: The UUID of the zone(s) to clean, multiple zones can be specified using comma separation
      required: true
      example: '"zone123456789" or "zone123456789,zone987654321"'
      selector:
        text:

# Servicio para limpiar un mapa específico
clean_map:
  name: Clean map
  description: Start cleaning a specific map.
  target:
    entity:
      domain: vacuum
      integration: kobold_vr7
  fields:
    map_uuid:
      name: Map UUID
      description: The UUID of the map to clean
      required: true
      example: "map123456789"
      selector:
        text:
